export const USER_LOGIN = "USER_LOGIN";
export const GET_DASHBOARD_WIDGETS = "GET_DASHBOARD_WIDGETS";
export const POST_DASHBOARD_WIDGET = "POST_DASHBOARD_WIDGET";
export const PUT_DASHBOARD_WIDGET = "PUT_DASHBOARD_WIDGET";
export const DELETE_DASHBOARD_WIDGET = "DELETE_DASHBOARD_WIDGET";