let initstate={
emailid:"",
password:"",
userid:"",
username:"",
loginstatus:"",
isAddRights:false,
isDeleteRights:false,
isEditRights:false,
loginmsg:"",
token:"",
type:"",
sessionId:"",
expiryTimestamp:"",
widgetData:[],
drilldownData:[],
userDetails:[],
user_dbStatus:false,
report_name:[],
report_details:[],
report_dbStatus:false,
report_object:{},
report_time:-1,
g_dbStatus:false,
g_dbMsg:"",
g_flag:"",
schedulerNames:[],
schedulerObject:{},
dashboardDropdown:{},
singleDashboardWidget:{}
}

export default initstate;